#!/usr/bin/env bash
#
# USAGE:
#   $ update_pack [packname]

main() {
  local packname="${1-ttaylorr}"

  parallel "\
    pushd {} >/dev/null
      git submodule update --init

      git checkout -q master
      git pull origin master
    popd >/dev/null" \
    ::: "$(list_submodules_in "vim/pack/$packname")"
}

list_submodules_in() {
  local dir="$1"

  git submodule \
    | awk '{ print $2 }' \
    | grep -e "^$dir"
}

main;
